### ISSUE TITLE
能否将悬浮显示的块，添加白色背景

### ISSUE THREAD

**Issue by pisceswb** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#16]
非常感谢作者提供这么棒的插件。
请问能否将悬浮显示的块，添加白色背景，这样就不会受到底部文本的影响导致看不清内容了。

另外，能否能够保存自己定义的块的样式，例如，设置了一个块即有边框，又有背景，下次能够直接使用，不用再自己添加代码了。
谢谢！

**Comment by Zuoqiu-Yingyi** [comment]
> 请问能否将悬浮显示的块，添加白色背景，这样就不会受到底部文本的影响导致看不清内容了。

可以使用如下 CSS 选择器自定义悬浮的块样式

```css
[plugin-custom-block~=position-sticky]:root .protyle-wysiwyg [data-node-id][custom-block-position~=sticky] {
    background-color: white;
}
```

> 另外，能否能够保存自己定义的块的样式，例如，设置了一个块即有边框，又有背景，下次能够直接使用，不用再自己添加代码了。

只能等我有时间再搞了
