### ISSUE TITLE
列表转表格后，建议对齐表格线

### ISSUE THREAD

**Issue by Tlonglan** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#6]
如下图，表格线没对齐的话，纵向的信息就比较难看清楚关系了，建议优化一下，感恩~

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-custom-block/assets/38731172/62703354-c14c-4001-a860-b6bcdc9d4df0)

**Comment by Zuoqiu-Yingyi** [comment]
使用 CSS 片段自定义 `min-width` 与 `max-width` 的方案设置宽度能接受吗❓

**Comment by Tlonglan** [comment]
> 使用 CSS 片段自定义 `min-width` 与 `max-width` 的方案设置宽度能接受吗❓

可以试试~ 请问下该怎么写呢，不会css :joy:

**Comment by Zuoqiu-Yingyi** [comment]
```css
:root {
    /* 列表看板视图 - 看板项最小宽度 */
    --custom-block-list-board-min-width: 16em;
    /* 列表看板视图 - 看板项最大宽度 */
    --custom-block-list-board-max-width: 16em;
    
    /* 列表表格视图 - 表格项最小宽度 */
    --custom-block-list-view-table-min-width: 8em;
    /* 列表表格视图 - 表格项最大宽度 */
    --custom-block-list-view-table-max-width: 8em;
    
    /* 列表导图视图 - 列表项最小宽度 */
    --custom-block-list-view-map-min-width: 8em;
    /* 列表导图视图 - 列表项最大宽度 */
    --custom-block-list-view-map-max-width: 8em;
}
```

其中 `1em` 表示一个汉字的宽度
该功能得等下次发版时才能上线
